### PR TITLE
Fun language

### PR DESCRIPTION
**Pull request by ehildenb**
Puts the FUN back in KAT!

### CODE REVIEW

**Review by lucaspena — DISMISSED** [review]
Looks good!

**Comment by ehildenb** [comment]
@lucaspena looks like we'll need strategies to test each program on before this passes. I guess lets fill in the ones that are SBCing correctly with the `compile` strategy, and the rest we can just do some exploratory strategies.

**Comment by ehildenb** [comment]
@lucaspena I've added `exec` as a test for each FUN program (in the *.strat files). I've only kept the output which worked (matched the results of `./kat run-orig SAME_PROGRAM.fun`). A few things we need to fix to get the remainder of the programs going:

-   Nondeterminism due to `strict` needs to be removed by replacing with uses of `seqstrict`.
-   Need separate strategy files for `*.imp` and `*.fun` files, I propose renaming a file `PROGRAM_NAME.strat` to `PROGRAM_NAME.imp.strat` (including language as an extension).
-   Need to investigate why the global integer generator counter starts from `0` when run with the original definition, vs starting from `1` when running with the strategy `exec`. This could be an OCaml vs Java backend thing. It causes the entire `<store>` cell to be shifted in the output of `exec`, which makes it hard to compare to the results of `exec` to vanilla `krun` automatically.

**Comment by ehildenb** [comment]
The minimum we need to do to get CI passing is the first two bullet points.

**Comment by ehildenb** [comment]
Alright, I've fixed the `strict` issue, the three remaining broken tests are:

`tests/collatz-all-upto.fun`, `tests/long-loop.fun`, and `tests/sum.fun`. This is because their strategy files clash with the names of the strategy files given  to the IMP programs.

**Pull request merged**
